name: docs
channels:
dependencies:
    # Base depends
  - python
  - pip

    # Package depends
  - numpy
  - matplotlib
  - scipy
  - pytest
  - sys

    # Pip-only installs
  - pip:
    - sphinx-autoapi
